---
- hosts: nater.sample.com
  gather_facts: no
  become: true

  pre_tasks:
    - name: check ubuntu release
      raw: cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d "=" -f2
      register: ubuntu_release
      changed_when: false

    - name: update apt cache
      raw: apt-get update
      changed_when: false

    - name: install python
      raw: apt-get install -yq python
      when: "{{ ubuntu_release.stdout| version_compare('16.04', '>=') }}"

    - name: check for 99-tuning.conf
      stat:
       path: /etc/sysctl.d/99-tuning.conf
      register: tuning_conf

  tasks:
    - name: enable packet forwarding in kernel
      when: tuning_conf.stat.exists == False
      block:

      - name: copy over tuning file
        template:
          src: 99-tuning.conf
          dest: /etc/sysctl.d/99-tuning.conf

      - name: update sysctl
        shell: sysctl --system

